### PR TITLE
Add nav 'What is SORSE?' on pages' right-side navs

### LINKED ISSUE #66: Link what is sorse in sidebar on front page
https://rse-leaders.github.io/SORSE20/faq/about/what-is-sorse should be in the sidebar

image

### PR DESCRIPTION
**Pull request by sdruskat**
Fixes #66 I hope :).

### CODE REVIEW

**Comment by sdruskat** [comment]
image

**Comment by Chilipp** [comment]
I'd actually put this under the FAQ navigation as it is part of the FAQ @sdruskat. Or do you think there will be more that we group under **SORSE20** in the *news* nav?

**Comment by sdruskat** [comment]
I don't mind either way, but the GDoc mentioned in should go in the right-hand nav on *all* pages?

> https://rse-leaders.github.io/SORSE20/faq/about/what-is-sorse should be linked in the sidebar on the front page and each of the other sections

**Comment by sdruskat** [comment]
We can try without an extra sub header, so that it's less in-your-face.

**Comment by Chilipp** [comment]
Good point. Can you *inherit* a nav? Do you know this?

**Comment by sdruskat** [comment]
As it's all YAML, I think inheritance would make this more complex than necessary. I've put in changes with an empty title, will try title-less as well.

**Comment by sdruskat** [comment]
Removing `title` field also works fine, as expected.

**Comment by sdruskat** [comment]
https://111-267395254-gh.circle-artifacts.com/0/SORSE20/index.html

**Comment by Chilipp** [comment]
@sdruskat: Thanks for this! As it should be included everywhere, I am okay with having SORSE20 as one item in the navigation, only *What is SORSE* as a child disturbs it. So I added it again and it links now to the front page (i.e. `/`). 

Actually, you can easily take items from another nav. Just use `&something` where you define it and `*something` where you want to use it (see https://github.com/RSE-leaders/SORSE20/pull/70/commits/20105e332fa7fac4574cf9971c11533c9e51ab32).

Are you okay with the way it looks now?

https://113-267395254-gh.circle-artifacts.com/0/SORSE20/index.html

**Comment by sdruskat** [comment]
Sure, good to go.

**Pull request merged**
