### PR TITLE
update be-rse logo

### PR DESCRIPTION
**Pull request by johanphilips**
The gitter avatar from the be-rse could be used as the logo. Ideally this should be hosted on the be-rse.org website, but for now linked via gitter.im. This is ready for review.

### CODE REVIEW

**Comment by Chilipp** [comment]
You're sure that this url is stable @johanphilips ? Alternatively we can also add the image to this repository, it does not need to be an external url

**Comment by Chilipp** [comment]
You'd just need to add the image file to /assets/images and add this path as the avatar

**Comment by vsoch** [comment]
I would +1 to just add the file to the repository, we can't be sure that it will always be available at that url!

**Comment by johanphilips** [comment]
made the change to a local asset, which is indeed safer.

**Comment by Chilipp** [comment]
thanks a lot @johanphilips :)

**Pull request merged**
