### PR TITLE
adding posts and example archive

### PR DESCRIPTION
**Pull request by vsoch**
As discussed in https://github.com/RSE-leaders/SORSE20/issues/15#issuecomment-642940625, this PR adds a simple setup to have posts (with categories), and we render them at the bottom of the home page as announcements:

image

(I suspect this would be moved up somewhere else or put on a sidebar, I'm just plopping it there to show how the syntax looks). And then each post is a dummy page for now:

image

And then I added an archive page to show posts by year, this could also be filtered by category (but doesn't have to be). This isn't currently linked from anywhere.

image

@Chilipp since you have vision for how you want the final thing to be, please take this and edit however you please! Details that need attention are:

 - where to put the link to post archive (and how to customize rendering the listing, e.g., adding categories, or even rendering different pages or sections for different categories)
 - how to format the url for posts (if we add a `category` to the frontend matter of the posts and use that instead of the tag then we could much better represent this in the url.
 - where to render posts (filtered to some subset) on the front page.

I don't intend for this to be perfect, but a good start that you can work from to tweak to the needs of the site.
Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by Chilipp** [comment]
You're really fast @vsoch :satisfied: I'll need to think about it as it's already pretty late over here :wink: thanks a lot!

**Comment by vsoch** [comment]
Yeah sounds good!

**Comment by Chilipp** [comment]
> how to format the url for posts (if we add a category to the frontend matter of the posts and use that instead of the tag then we could much better represent this in the url.

Yes, I think using categories is the way to go here. Maybe *Announcements* also does not sound very nice. Shall we use *News* instead and use this as the corresponding category?

> where to render posts (filtered to some subset) on the front page

this depends what we will have on the front page. If we go for what I proposed in https://github.com/RSE-leaders/SORSE20/issues/15#issuecomment-641529419 and only have a short welcome text, I'd put the posts and events below this text.

**Comment by Chilipp** [comment]
Yes, actually I think this can be merged, right @vsoch? Then I update #64

**Pull request merged**
