### PR TITLE
Drafting a privacy policy page

### PR DESCRIPTION
**Pull request by bast**
This is a draft and it is not complete but I need feedback. Refers to #80.

It currently does not really address points 2-4 because I was unsure about few questions and a problem (below):
- right of information: declare which data you collect and why in an understandable fashion
- right of access: declare how they can access the data if they want to.
- right of rectification: declare how they could demand we delete the data.
- right to object: declare how they can object that we process their data.

Questions:
- Will the participants (not the presenters) also register?
- If yes, using Indico?
- If they register, where/how and how long are we storing their data?

Problem:
- Does a talk author have the right to be forgotten? But what if the talk is published with a DOI? We don't really want to revoke that DOI later.

Please feel free to commit changes to this source branch to improve this PR.

### CODE REVIEW

**Comment by Chilipp** [comment]
Thanks a lot @bast! I'll have a closer look later today : smiley:

**Comment by Chilipp** [comment]
Hi @bast!

> Will the participants (not the presenters) also register?

According to @ClaireWyatt in #97 (I don't know, where this was decided), each participant will have to register using a google form. The participation details will, however, be deleted after each event.

see #109 and https://github.com/RSE-leaders/SORSE20/blob/e9ce9c47d976e98480aba3ddd3d62afa544632d4/_faq/about/03-costs.md in particular

> Does a talk author have the right to be forgotten?

Each talk will get a dedicated site on our webpage including the abstract and the contact details of the corresponding author. If the author wants to be removed, this page and all associated commits will be removed (see @johanphilips comment in #80 about https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository)

> But what if the talk is published with a DOI? We don't really want to revoke that DOI later.

No, we don't. We can remove any detail of the author by modifying the entry on Zenodo, but we cannot remove the abstract and the DOI (see https://about.zenodo.org/policies/)

**Comment by bast** [comment]
Thanks for placing it in the footer and thanks for the answers. I will send a commit addressing the points that I was unsure about earlier.

**Comment by Chilipp** [comment]
looks great to me and reads very good and clear! Thanks a lot @bast! For me, this is ready to be reviewed, or do you want to make more changes @bast?

@cc-a it would be great if you could have  look into the [Author information](https://185-267395254-gh.circle-artifacts.com/0/SORSE20/privacy/index.html#author-information) section to make sure the website and the Indico form do not disaggree

**Comment by bast** [comment]
Ready for review (sorry I forgot to do that earlier).

**Comment by Chilipp** [comment]
@ClaireWyatt: Could have a quick look on this?

https://185-267395254-gh.circle-artifacts.com/0/SORSE20/privacy/index.html

**Comment by johanphilips** [comment]
Reply to mail didn’t come through...Looks good, but I would more explicitly state that:
- by registering you give consent to store those data
- upon request your data can be removed
- we keep this information until ...
- you have the right to access your data anytime by contacting us via ...
- we only store data that you have provided us via the registration form, no derivatives based on Google Search, LinkedIn, Facebook, orchid, ...

**Comment by Chilipp** [comment]
thanks @johanphilips. @bast: Do you have time to implement these suggestions?

**Comment by bast** [comment]
> Do you have time to implement these suggestions?

I will now soon send a commit addressing these.

**Comment by Chilipp** [comment]
Thanks a lot @bast ! @ClaireWyatt also posted something in #141

**Comment by bast** [comment]
Hopefully done. Please check :-)

**Pull request merged**
