### PR TITLE
typos in rse dh topic

### PR DESCRIPTION
**Pull request by florianthiery**
found some typos sry @Chilipp

### CODE REVIEW

**Comment by Chilipp** [comment]
Alright, just merge it when you are okay with it (you should have the right to)

**Comment by florianthiery** [comment]
it sais:

Merging is blocked
The base branch restricts merging to authorized users. Learn more about protected branches.

**Comment by Chilipp** [comment]
good to know! Thanks @florianthiery. It should now be possible for you

**Comment by florianthiery** [comment]
yep!

**Pull request merged**
