### PR TITLE
Added Topic Bazaar

### LINKED ISSUE #6: Add page for Topic Bazaar
- [x] Page added in the programme folder [programme](_pages/programme)
- [x] Page listed in [navigation.yml](_data/navigation.yml)
- [x] internal link added to [programme_teams.yml](_data/committee/programme_teams.yml)

### PR DESCRIPTION
**Pull request by TeriForey**
Added the page, links and short paragraph for the topic bazaar. 

Still missing a couple of links but we haven't got them ready yet.

closes #6

### CODE REVIEW

**Comment by TeriForey** [comment]
@Chilipp I've added the topics (those from deRSE that are happy to stay within the bazaar) and a google form. Could you please review it again? Thanks!

**Comment by Chilipp** [comment]
It's really nice! I like the style and it looks good on a mobile device =) How do people edit their topic in case they want to change or update something? Should go via PR to this repository?

**Comment by Chilipp** [comment]
An alternative way to the very long YAML file would be a collection. We can keep the style with the cards, but you would have additionally one markdown formatted file per topic that looks like

```markdown
---
title: Developing, Distributing and Testing Research Software with Anaconda
type: Workshop
contributors: |
  This workshop is supposed to be community-driven and I have no clue 
  about whether it is useful or not! Therefore, please let me know what 
  you think and particulary, if you think this might be useful for you or 
  others by the 1st of March at the latest.
name: Philipp S. Sommer
email: philipp.sommer@hzg.de
looking: true
---
The distribution of research software is challenging due to the complexity of 
dependencies and the speed of technological advancement. Automation and 
standardization of this process speeds up the development process, as well 
as the communication and interaction with the users. This is particularly 
important for research software, as the number of developers are limited and 
labor for infrastructural maintenance is usually not available. In this workshop
we want to discuss how the package manager anaconda (https://conda.io) can
be used to automate such a process. The package manager works for various 
different programming languages, and operating systems, and provides with 
the conda-forge channel a community-based platform to distribute and build 
your own packages.
```

If you like this idea, I am happy to convert the YAML-file accordingly.

**Comment by TeriForey** [comment]
Thanks @Chilipp 

Would having it as a markdown collection allow us to add formatting within the description? I know that some people had numbered lists for example and it might be nice to resurface that.

**Comment by Chilipp** [comment]
Yes, that would work @TeriForey

**Comment by TeriForey** [comment]
Awesome, thanks! If you could convert the file that would be great, I'm not sure I know what a collection needs to look like.

**Comment by Chilipp** [comment]
alright @TeriForey, I am done with it. It was a bit more work than I initially expected I have to admit, and I had to fight a bit with the layouts. However, here is the summary:

1. I added one file per topic and removed the topics.yml file, and added the bazaar collection to _config.yml in https://github.com/RSE-leaders/SORSE20/pull/35/commits/49c79431420cc2018916321b177bfdd5d883a3cd
2. As this is now using posts, I had to change your topic.html (now topic-card.html) a bit (7492a0420f9ad4dab92d748d948d955c5692b5dc).
3. The topics use the topics.html layout, it is essentially the same as a default [single](https://github.com/mmistakes/minimal-mistakes/blob/master/_layouts/single.html) layout, but adds the meta data of the topic using topic-summary.html

https://github.com/RSE-leaders/SORSE20/blob/3d766bce5ffe68d03557b8bc2e61bfa62b157963/_layouts/topic.html#L47

The results can be seen here: https://125-267395254-gh.circle-artifacts.com/0/SORSE20/programme/bazaar/index.html

and an example post is here: https://125-267395254-gh.circle-artifacts.com/0/SORSE20/programme/bazaar/examples-and-discussion-how-to-do-good-tutorials-for-research-software/index.html

The contact person is shown on the upper left (see screenshot below) but I wonder whether it makes sense to also add this with topic-summary.html

**Comment by TeriForey** [comment]
Thanks @Chilipp! 

I think you're right about the summary - it doesn't look right to have the name suddenly appearing in the sidebar. If we could have the same kind of summary as on the main topic page at the bottom of each post that would be better

**Comment by Chilipp** [comment]
> If we could have the same kind of summary as on the main topic page at the bottom of each post that would be better

alright @TeriForey, done with bd01e748410a190c9f4a76a6ad8f7f9ff4201432, see https://135-267395254-gh.circle-artifacts.com/0/SORSE20/programme/bazaar/rse-education/index.html. 

I also changed the navigation for the topics with 8cea6ffbacd2dcd671ba289331e046130eba378c such that they only link back to the other topics

image

From my perspective, this PR can be merged now

**Comment by TeriForey** [comment]
I've just updated a couple of the topics to re-apply the formatting that had been lost. Looks good to me 👍

**Comment by Chilipp** [comment]
alright, I made a small change to the layout as it is not necessary to copy the entire single layout as I did initially with a10ca5bc99a0600661c395e3c6c5b2427c558c79, instead I can just use the inheritance of layouts. I'll merge it then.

**Pull request merged**
