### PR TITLE
Add be-RSE to the list of national RSE chapters

### PR DESCRIPTION
**Pull request by Chilipp**
This PR adds be-RSE to the list of national RSE chapters and associates Johan Philips with it.

https://140-267395254-gh.circle-artifacts.com/0/SORSE20/contact/chapters/index.html
https://140-267395254-gh.circle-artifacts.com/0/SORSE20/contact/chapters/index.html#beRSE

### CODE REVIEW

**Comment by johanphilips** [comment]
👍 two remarks:
- would it be possible to also add https://gitter.im/be-rse/ in the list of contact details?
- I am currently still listed at UK RSE as well. But I could send a different PR to update my details, if you'd like. Also I am part of the program and organising committee :-)

**Comment by Chilipp** [comment]
sure, no problem. I'll fix both points when I am back on my laptop this evening. thanks @johanphilips!

**Comment by Chilipp** [comment]
alright @johanphilips, I updated your teams with 007fe8949681635e70c37eb0699dc659922e1e6e and I added gitter with d9ceadffff76fd4bf0f51874603f2fec3695f58a

 

can this then be merged?

**Comment by vsoch** [comment]
You know, if you flipped the p (or speaking bubble in the graphic) on it's head, you'd have a "b" for Belgium!

**Comment by Chilipp** [comment]
Or you mirror the "d" in the de-RSE logo and you have a be-RSE logo :wink:

**Comment by vsoch** [comment]
:exploding_head: !!!

**Comment by johanphilips** [comment]
So if I rip off both logos, we get something 'original' X-D
@Philipp, yes you can merge!

**Comment by johanphilips** [comment]
Thanks, regarding the logo, we could use the avatar from Gitter:
https://avatars-01.gitter.im/group/iv/1/5eea1690d73408ce4fe727d8?s=144

**Comment by vsoch** [comment]
@johanphilips that's beautiful!

**Pull request merged**
