### PR TITLE
Add Code of Conduct to the website

### LINKED ISSUE #93: Code of Conduct
Please could this go on the website , linked from the landing page across the top menu?
---
**Code of Conduct**

We value the participation of each stakeholder and want all participants to have an enjoyable and fulfilling experience. Accordingly, all participants are expected to show respect and courtesy to other participants throughout the events and through all communication channels, including but not limited to the zoom room, zoom webinar, youtube channel, discord platform and the slack channel.  

To make clear what is expected, all participants, speakers, exhibitors, organisers and volunteers involved in SORSE are required to conform to the following Code of Conduct. Organisers will enforce this code. 

**Summary**

SORSE organisers are dedicated to providing a harassment-free experience for everyone. We do not tolerate harassment of participants in any form.  All communication should be appropriate for a professional audience including people of many different backgrounds. 

Be kind to others. Do not insult or put down other attendees.

Behave professionally. Remember that harassment and exclusionary jokes are not appropriate. Do not send any unprofessional messages to other participants, including but not limited to private messages in Slack, Zoom and Discord.

Participants violating these rules may be asked to leave the event at the sole discretion of the SORSE organisers.

Thank you for helping make this a welcoming, friendly event for all.

**Clarifications**

Harassment includes offensive communication related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

Participants asked to stop any harassing behaviour are expected to comply immediately.

Be careful in the words that you choose. Remember that words can be offensive to those around you. Offensive jokes are not acceptable at the SORSE events. Excessive swearing is not appropriate.

If a participant engages in behaviour that violates this code of conduct, the SORSE organisers may take any action they deem appropriate, including warning the offender or expulsion from the event and it may affect the offenders' ability to join future events.

**Contact Information**

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact any member of the Code of Conduct team:

    Claire Wyatt, Software Sustainability Institute, RSE Community Manager, c.wyatt@soton.ac.uk

    Marion Weinzierl, Durham University, 

The Code of Conduct team is happy to assist those experiencing harassment to feel safe for the duration of the event. We value your participation.

**Procedure for Reporting Harassment**

You can find the Attendee Procedure For Reporting Harassment here.

**Acknowledgement**

This Code of Conduct was adapted from the example policy for the CW20 and also from the Geek Feminism wiki, created by the Ada Initiative and other volunteers, which is under a Creative Commons Zero license.

-----

(New page - linked from the sentence above "You can find the Attendee Procedure For Reporting Harassment here."

**Attendee Procedure For Reporting Harassment**

Please contact either member of the Code of Conduct (CoC) team:

    Claire Wyatt, Software Sustainability Institute, RSE Community Manager, c.wyatt@soton.ac.uk

    Marion Weinzierl, Durham University, marion.b.weinzierl@gmail.com

The CoC team is prepared to handle the incident. Both of our team members are informed of the Code of Conduct policy and guide for handling harassment at the workshop. There will be a mandatory CoC Committee meeting just prior to the series launch when this will be reiterated as well.

Report the harassment incident via private message in Slack or as an email to a member of the CoC team. All reports are confidential.

When reporting the event to a CoC team member, try to gather as much information as available, but do not interview people about the incident. The CoC team member will assist you in writing the report/collecting information.

    The important information we need consists of:

        Identifying information (name) of the participant doing the harassing

        The behaviour that was in violation

        The approximate time of the behaviour (if different than the time the report was made)

        The circumstances surrounding the incident

        Other people involved in the incident

The CoC team is well informed on how to deal with the incident and how to further proceed with the situation.

Even though this is an online workshop if at any time you feel that your personal safety is in jeopardy then contact your local Police / law enforcement service.

**Acknowledgement**

This procedure has been adopted from the Ada Initiative's guide titled "workshop anti-harassment/Responding to Reports”.

### LINKED ISSUE #103: Change to CoC page
please change marion's email to marion.weinzierl@durham.ac.uk 

Please add the following person to the CoC team list:

Christopher Cave-Ayland, Imperial College London, c.cave-ayland@imperial.ac.uk

### PR DESCRIPTION
**Pull request by Chilipp**
This PR adds the code of conduct and associates @ClaireWyatt and @MarionBWeinzierl with the Code of Conduct team.

Please review the following pages:

* [the front page](https://175-267395254-gh.circle-artifacts.com/0/SORSE20/index.html), where the CoC appears in the sidebar and the footer
* the [CoC page](https://175-267395254-gh.circle-artifacts.com/0/SORSE20/code-of-conduct/index.html)
* the [report page](https://175-267395254-gh.circle-artifacts.com/0/SORSE20/code-of-conduct/report.html)

closes #93, closes #103

### CODE REVIEW

**Comment by ClaireWyatt** [comment]
Doesn't seem to address 103? Chris Cave-Ayland as a CoC team member also.

**Comment by Chilipp** [comment]
My apologies @ClaireWyatt. Chris @cc-a is now also a part of the CoC team

see https://201-267395254-gh.circle-artifacts.com/0/SORSE20/code-of-conduct/index.html
and https://201-267395254-gh.circle-artifacts.com/0/SORSE20/code-of-conduct/report.html

otherwise everything from #103 should be covered, right?

**Comment by sdruskat** [comment]
I've also added a `h1` header, as I think this makes it easier for people to figure out where they are on the page. I haven't checked across the site, but I think this should be on every page.

**Comment by Chilipp** [comment]
> I haven't checked across the site, but I think this should be on every page.

@sdruskat: The `h1` header is inserted with the `title` from the front matter

```yaml
---
tite: Code of Conduct
permalink: /code-of-conduct/
sidebar:
  nav: coc
toc: true
toc_sticky: true
---
```

So there is no need to add it manually. Now you have it twice (see https://202-267395254-gh.circle-artifacts.com/0/SORSE20/code-of-conduct/index.html and the screenshot below)

image

**Comment by ClaireWyatt** [comment]
Kirsty Pringle would like to also be on the CoC team so please could you add her and her email address k.pringle@leeds.ac.uk

**Comment by Chilipp** [comment]
> Ah, it wasn't inserted in the Circle artifact before:

hmm, no idea what's going on here. I'll have a look @sdruskat

**Comment by Chilipp** [comment]
there was a typo @sdruskat, solved with  https://github.com/RSE-leaders/SORSE20/pull/113/commits/1d2f2b473a1cf119efd61a2ceb30cf1d358503bc

**Comment by Chilipp** [comment]
> Kirsty Pringle would like to also be on the CoC team so please could you add her

done @ClaireWyatt, see https://206-267395254-gh.circle-artifacts.com/0/SORSE20/code-of-conduct/index.html

**Pull request merged**
